# Generated by Django 3.1.4 on 2021-01-27 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Вариант ответа')),
                ('right', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('high', models.BooleanField(default=False)),
                ('answers', models.ManyToManyField(related_name='question', to='doc_tables.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент для теста')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Названия теста')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_tests', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(to='doc_tables.Question')),
            ],
        ),
        migrations.CreateModel(
            name='TestUUID',
            fields=[
                ('slug', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('right_answer', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='doc_tables.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тест пользвателя',
                'verbose_name_plural': 'Тесты пользователей',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='unique_slug',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doc_tables.testuuid'),
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Excel', verbose_name='Файл эксель')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки файла')),
                ('archive_date', models.DateTimeField(auto_now=True, verbose_name='Время отправки в архив')),
                ('archive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='work_tables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Файл Excel',
                'verbose_name_plural': 'Файлы Excel',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='photoUsers')),
                ('phone', models.CharField(blank=True, max_length=300, null=True)),
                ('work', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Имя файла')),
                ('json_data', models.TextField(blank=True, null=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='doc_tables.tables')),
            ],
        ),
    ]
