# Generated by Django 3.1.4 on 2021-01-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tests',
            name='anonym_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
