# Generated by Django 3.1.4 on 2021-02-05 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_tables', '0007_test_childrentest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='childrenTest',
        ),
        migrations.AddField(
            model_name='test',
            name='baseTest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrenTest', to='doc_tables.test'),
        ),
    ]
