# Generated by Django 3.1.4 on 2021-02-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_tables', '0009_user_tests_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tests',
            name='all_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_tests',
            name='content_test_for_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
