# Generated by Django 3.1.4 on 2021-02-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_tables', '0010_auto_20210207_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tests',
            name='date_end',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
