# Generated by Django 3.1.4 on 2021-02-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_tables', '0011_user_tests_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tests',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
